# YAML de configuration, 05.06.2026 - CGN model v1.2

# Configuration simplifiée du bateau CGN "Vevey"
# Coefficients validés avec R. Baur le 18.12.2025
# - rendement du group "Genset" calculé en fonction de la vitesse
# [0.111383, 0.035626, 0.004367, -0.000569] (C0-C3 -> m/s to η genset group)
# - conversion de la vitesse en puissance à l'arbre des roues à aubes
# [0.0, -209.0, 1904.4, 531.36, 93.312] (C0-C4 -> m/s to W à l'arbre)


vessel:
  name: "Vevey"
  vessel_type: "DE"

simulation:
  dt: 1.0  # [s]

profiles:
  - id: "hotel_load"
    kind: "constant"
    unit: "W"
    value: 100e3  # [W]

  - id: "speed"
    kind: "nav_speed"
    unit: "m/s"
    source: "cgn_croisieres/all"
    select:
      by: "croisiere"
      cruise_name: "Lavaux - Haut-Lac"
    params:
      acc: 0.05          # [m/s²]
      dec: 0.05          # [m/s²]
      v_croisiere: 7     # [m/s]
      allow_delay: true

adapters:
  - id: "shaft_power_from_speed"
    kind: "speed_to_power_poly"
    source: "speed"
    unit_in: "m/s"
    unit_out: "W"
    params:
      coeffs: [0.0, -209.0, 1904.4, 531.36, 93.312]  # coefficients "m/s" to  "W"

  - id: "eta_from_speed"
    kind: "speed_to_eta_poly"
    source: "speed"
    unit_in: "m/s"
    unit_out: "-"
    params:
      coeffs: [0.111383, 0.035626, 0.004367, -0.000569]  # coefficients "m/s" to η genset

inputs:
  - id: "shaft_demand"
    bus: "shaft"
    source: "shaft_power_from_speed"
    sign: "consume"

  - id: "navops"
    bus: "elec_power"
    source: "hotel_load"
    sign: "consume"

solver:
  mode: "inverse"

buses:
  - id: "shaft"
    carrier: "Mechanical"

  - id: "elec_power"
    carrier: "Electrical"

  - id: "fuel"
    carrier: "Chemical"

converters:
  - id: "motor"
    from_bus: "elec_power"
    to_bus:   "shaft"
    kind: "constant_eta"
    params:
      eta: 0.9   # [-]

  - id: "genset"
    from_bus: "fuel"
    to_bus:   "elec_power"
    kind: "variable_eta"
    params:
      eta_default: 0.38   # [-]
      eta_source: "eta_from_speed"

storages:
  - id: "fuel_tank"
    bus: "fuel"
    vector_energy: "diesel"
    vector_params:
      pci_basis: "mass"
      pci_value: 11.86  # [kWh/kg]
      pci_mass_unit: "kWh/kg"
      density_kg_m3: 840.0  # [kg/m³]
    initial_level:
      value: 1000  # [litres]
      unit: "l"
