# environment.yml (standard + dev)
name: cgnmodel

channels:
  # "nodefaults" is similar to "-c conda-forge --override-channels" but for yml
  - conda-forge
  - nodefaults

dependencies:
  # --- Python runtime ---
  - python=3.13.13

  # --- Core data stack ---
  - pyyaml=6.0.3
  - pydantic=2.12.5
  - numpy=2.4.3
  - matplotlib=3.10.8
  - pandas=3.0.2

  # --- Graph algorithms ---
  - networkx=3.6.1

  # --- Web MVP ---
  - dash=3.4.0
  - plotly=6.6.0
  - dash-extensions=2.0.5
  - dash-pydantic-form=0.18.3
  - dash-pydantic-utils=0.18.3
  - dash-mantine-components=2.6.1

 # --- Dev & tests ---
  - pytest=9.0.3
  - ruff=0.15.11
  - black=26.3.1

  # --- IDE optionnel ---
  - spyder

  # --- Packaging ---
  - pip
  
