# environment.yml (standard + dev)
name: cgnmodel

channels:
  # "nodefaults" is similar to "-c conda-forge --override-channels" but for yml
  - conda-forge
  - nodefaults

dependencies:
  # --- Python runtime ---
  - python>=3.13

  # --- Core data stack ---
  - pyyaml
  - pydantic
  - numpy
  - matplotlib
  - pandas
  - pint # gestion des unités (optionnel)
  # - pyarrow

  # --- Graph algorithms ---
  - networkx

  # --- Web MVP ---
  - dash
  - plotly # dépendence de dash
  - dash-extensions
  - dash-pydantic-form

  # # --- Dev & docs (optional but recommended) ---
  - pytest
  - ruff
  - black
  
  # - mkdocs
  # - mkdocs-material
  # - mkdocstrings
  # - mkdocstrings-python

  # --- IDE ---
  - spyder
  - spyder-kernels

  # --- Packaging ---
  - pip
  
  # --- Instalation projet cgn_model---
  # - pip install . # mode normal
  # - pip install -e . # mode éditable