blocks: # level 2
# all variables are time-dependent
  propulsion_path:
    in: v [m/s]
    out: T_shaft [N·m], omega [rad/s], P_shaft [W]
  prime_mover:
    in: T_shaft [N·m], omega [rad/s], P_shaft [W]
    out: # specific, fuel_rate or P_elec_prop
    prime_mover_DE:
      in: # generic, master definded
      out: P_elec_prop [W]
    prime_mover_Steam:
      in: # generic, master definded
      out: fuel_rate [kg/s]
  electrical_bus:
    in: P_elec_prop [W], P_HL [W] # P_elec_prop is optionnal, P_HL is time-dependent
    out: # allocation to GensetGroup [W]
  genset_group:
    in: P_bus_demand [W]
    out: fuel_rate [kg/s]
  fuel_tank:
    in: fuel_rate [kg/s]
    out: fuel_cum [kg], volume_used [m3], volume_remaining [m3]



C'est parfait !

J'ai fait un petit récap des in/out dans un ".yml" (informatif) parce que de mon sens, pour PrimeMover, tu as inversé les in/out

Encore 2 questions :
- Si j'ai des carburant gazeux ça vas aussi correctement avec [kg/s] ? ou il faut mettre un truc comme "Nm³/h" ?
- Pour "genset_group"
