vessel:
  name: "Vevey"
  type: "DE"
  
profil_vitesse:
    coefs:
      [0.2, 0.3, -2, ..]

solver:
  mode: "inverse"

buses:
  - {id: "Mechanical:shaft", carrier: "Mechanical"}
  - {id: "Electrical:main",  carrier: "Electrical"}
  - {id: "Chemical:fuel",    carrier: "Chemical"}

inputs:
  - {id: "shaft_demand", bus: "Mechanical:shaft"}
  - {id: "navops",       bus: "Electrical:main"}

converters:
  - id: "genset"
    from_bus: "Chemical:fuel"
    to_bus:   "Electrical:main"
    kind: "constant_eta"
    params:
      eta:  0.38 
  - id: "motor"
    from_bus: "Electrical:main"
    to_bus:   "Mechanical:shaft"
    eta:  0.9    # Fallback sur "constant_eta" si "kind" non renseigé et "eta" présent au top-level