# config_copli_251212.yaml
   
vessel:
  name: "Vevey"       # nom du bateau, à titre infortif (pas utilisé pour l'instant)
  vessel_type: "DE"   # type de bateau, à titre infortif (pas utilisé pour l'instant)

simulation:
  dt: 1.0             # [s], interval de temps entre les valeurs des profils, unité toujours en seconde

profiles:
  # 1) Profil constant
  - id: "hotel_load"                  # id unique de "l'objet"
    kind: "constant"                  # type de profil, ici profil constant
    unit: "W"                         # unité du profil, ici 100'000 W
    value: 100000

  # 2) Vitesse issue de l’horaire CGN (une course)
  - id: "speed"                       # id unique de "l'objet"
    kind: "nav_speed"                 # type de profil, ici selon horaire CGN
    unit: "m/s"                       # unité du profil produit (toujours m/s depuis l'horaire)
    source: "cgn_croisieres/all"      # dataset interne avec les horaires
    select:
      by: "cruise"                    # "cruise" | "course" | "leg"
      cruise_name: "Lavaux - Haut-Lac"           # si by="cruise"
      course_no: 982                                         # si by="course"
      leg: { from_port: "Rolle", to_port: "Yvoire" }         # si by="leg"
    params:                           # paramètres du MRUA
      acc: 0.05                       # [m/s²]
      dec: 0.05                       # [m/s²]
      v_croisiere: 7.0                # [m/s]
      allow_delay: true               # Ratrappe le retard si c'est possible

adapters:
    # 1) vitesse -> puissance (polynôme)
  - id: "shaft_power_from_speed"      # id unique de "l'objet"
    kind: "speed_to_power_poly"       # type d'adaptateur, gestion des équations et des unités
    source: "speed"                   # id du profil en entrée
    unit_in: "m/s"                    # l’adapter attend m/s
    unit_out: "W"                     # et produit des Watts
    params:
      coeffs: [0.0, -209.0, 1904.4, 531.36, 93.312]    # coefficients polynomial vitesse "m/s" to puissance "W"

inputs:
    # 1) Demande de puissance à l'arbre de la roue à aubes
  - id: "shaft_demand"                # id unique de "l'objet"
    bus: "shaft"                      # id du bus où est raccordé cet entrée
    source: "shaft_power_from_speed"  # id de l'entrée, ici un adaptateur
    sign: "consume"                   # convention de signe, "toujours consomation"

    # 1) Demande de puissance électrique directe (hélices d'étrave, cuisine, etc.)
  - id: "navops"
    bus: "elec_power"
    source: "hotel_load"              # id de l'entrée, ici directement le profil
    sign: "consume"

# Mode de calcul (résolution énergétique), ici commence par la fin et remonte au stockage
solver:
  mode: "inverse"

# Transporteur d'énergie, sommateur. Le solver éfféctue des bilans sur les "bus"
buses:
  - id: "shaft"                       # id unique de "l'objet"
    carrier: "Mechanical"             # type d'énergie transportée/sommée (informatif)
  - id: "elec_power"
    carrier: "Electrical"
  - id: "fuel"
    carrier: "Chemical"

# Convertisseurs d'énergie, équations.
# Le solver transfert l'éneregie d'un bus à l'autre en passant par les convertisseurs.
converters:
  - id: "genset"                      # id unique de "l'objet"
    from_bus: "fuel"                  # id du bus en entrée, selon le sens physique
    to_bus:   "elec_power"            # id du buis en sortie, selon le sens physique
    kind: "constant_eta"              # type de convertisseur, ici rendement constant
    params:
      eta: 0.38                       # [-], rendement

  - id: "motor"
    from_bus: "elec_power"
    to_bus:   "shaft"
    kind: "constant_eta"
    params:
      eta: 0.9
